### PR TITLE
Use Common Expression Language as single expression lang in spec

### PR DESCRIPTION
**Pull request by tsurdilo**
**Many thanks for submitting your Pull Request :heart:!**

**Please specify parts this PR updates:**

- [x] Specification
- [x] Examples
- [x] Schema
- [x] Roadmap
- [ ] Use Cases
- [ ] Community
- [ ] Website
- [x] SDK
- [ ] TCK
- [ ] Other

**What this PR does / why we need it**:

Sets the Common Expression Language (CEL) as single expression lang to be used in the spec. 

Addresses issue https://github.com/cncf/wg-serverless-workflow/issues/48

Updates Spec doc, examples, schema and the Java SDK

**Special notes for reviewers**:

**Additional information (if needed):**

### CODE REVIEW

**Comment by tsurdilo** [comment]
@ricardozanini this change requires an update to the Go SDK as it changes the workflow schema a little.

**Comment by tsurdilo** [comment]
rebased

**Comment by ricardozanini** [comment]
> @ricardozanini this change requires an update to the Go SDK as it changes the workflow schema a little.

Once you merge this, I'll update the SDK. Thanks for the heads up!

**Comment by tsurdilo** [comment]
rebased

**Comment by tsurdilo** [comment]
rebased

**Pull request merged**
