### PR TITLE
Markdown fixes

### PR DESCRIPTION
**Pull request by manuelstein**
**Many thanks for submitting your Pull Request :heart:!**

**Please specify parts this PR updates:**

- [ ] Specification
- [X] Examples
- [ ] Schema
- [ ] Roadmap
- [X] Use Cases
- [ ] Community
- [ ] Website
- [ ] SDK
- [ ] TCK
- [ ] Other

**What this PR does / why we need it**:
Our documents use inline HTML image tags, markdown-style images would be preferred.
Personal motivation is to use markdown-link-check to include the image links.

**Special notes for reviewers**:

**Additional information (if needed):**

### CODE REVIEW

**Comment by manuelstein** [comment]
Sorry, my first attempts somehow caught up tsurdilo's latest commits to master (guess I forgot to fetch before rebase)

**Comment by tsurdilo** [comment]
@manuelstein oh wow this is cool. i will check out your branch and look at all the images locally asap. Great work!

**Comment by tsurdilo** [comment]
@manuelstein there was also some mention that we could move to SVG images in one of our meetings. Maybe in the future we could look into this if you find it useful.

**Comment by tsurdilo** [comment]
@manuelstein looking at the images on your branch they look somewhat blurry, is there a way to fix that? Also is it not possible to center the images as they are now when using markdown images??
Just to show you one example , maybe I'm blind:

** Before **
Screen Shot 2020-06-12 at 10 04 40 AM

** After **
Screen Shot 2020-06-12 at 10 04 47 AM

**Comment by manuelstein** [comment]
Yes, maybe the approach to automate link checking should be parsing the inline HTML img tags.

**Pull request closed without merging**
